In [4]:
# 导入pytorh库
import torch

In [5]:
x = [2, 9, 4, 16, 23, 35]

In [6]:
# 检查x是否为tensor对象
torch.is_tensor(x)

False

In [7]:
y = torch.rand(1, 2)
y

tensor([[0.5702, 0.0547]])

In [8]:
torch.is_tensor(y)

True

In [9]:
# 统计tensor中的元素number elements
torch.numel(y)

2

In [10]:
# 创建全0的tensor
z = torch.zeros(3, 3, 3)
z

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [11]:
torch.numel(z)

27

In [12]:
# 将numpy转换为tensor
import numpy as np
x = np.array([3, 4, 5, 6, 7])
y = np.array([0.1, 0.3, 0.6])
z = np.array([0.1, 3, 0.6])

In [13]:
torch.from_numpy(x)

tensor([3, 4, 5, 6, 7], dtype=torch.int32)

In [14]:
torch.from_numpy(y)

tensor([0.1000, 0.3000, 0.6000], dtype=torch.float64)

In [15]:
torch.from_numpy(z)

tensor([0.1000, 3.0000, 0.6000], dtype=torch.float64)

In [16]:
# 切分 linspace
torch.linspace(2, 10, steps=10)

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])

In [17]:
# 均匀分布，生成元素值在0-1之间均匀分布的随机张量
torch.rand(10)
torch.rand(2,3)

tensor([[0.2687, 0.3693, 0.1519],
        [0.6352, 0.4602, 0.7484]])

In [18]:
# 正态分布，均值为0，方差为1
torch.randn(10)

tensor([ 1.9712,  0.6375,  0.3640, -0.2195,  1.1766, -1.5661,  0.0505,  0.0549,
        -1.2120,  0.2576])

In [19]:
# 选择随机数
torch.randperm(10)

tensor([3, 0, 1, 7, 6, 5, 9, 2, 4, 8])

In [20]:
# 生成一个区间数
torch.arange(10, 30, 5)

tensor([10, 15, 20, 25])

In [21]:
# 获取行或者列的最小值和最大值的索引
x = torch.randint(1, 99,(3,3))
x

tensor([[79, 28, 61],
        [ 1, 22, 25],
        [79, 56, 25]])

In [22]:
torch.argmax(x, dim=0)

tensor([0, 2, 0])

In [37]:
torch.argmin(x, dim=1)

tensor([0, 0])

In [24]:
# 连接
x = torch.randint(1,10,(2,3))
x

tensor([[7, 4, 3],
        [5, 8, 9]])

In [25]:
torch.cat((x, x))

tensor([[7, 4, 3],
        [5, 8, 9],
        [7, 4, 3],
        [5, 8, 9]])

In [26]:
torch.cat((x,x), dim=1)

tensor([[7, 4, 3, 7, 4, 3],
        [5, 8, 9, 5, 8, 9]])

In [27]:
# chunk切块
a = torch.randint(1, 10,(3,3))
a

tensor([[8, 9, 4],
        [9, 7, 9],
        [4, 5, 8]])

In [28]:
torch.chunk(a, 2, 0)

(tensor([[8, 9, 4],
         [9, 7, 9]]),
 tensor([[4, 5, 8]]))

In [29]:
torch.chunk(a, 2, 1)

(tensor([[8, 9],
         [9, 7],
         [4, 5]]),
 tensor([[4],
         [9],
         [8]]))

In [30]:
# split 分割
x = torch.randn((3,3))
x

tensor([[ 2.5204, -0.1978,  1.0663],
        [ 1.3488,  1.8815,  0.5075],
        [ 1.6157,  0.4196, -1.1037]])

In [31]:
torch.split(x, 2, 1)

(tensor([[ 2.5204, -0.1978],
         [ 1.3488,  1.8815],
         [ 1.6157,  0.4196]]),
 tensor([[ 1.0663],
         [ 0.5075],
         [-1.1037]]))

In [32]:
# 转置
x = torch.tensor([[1,2],[3,4]])
x


tensor([[1, 2],
        [3, 4]])

In [33]:
x.t()

tensor([[1, 3],
        [2, 4]])

In [34]:
# tensor运算
x = torch.tensor([[1,2], [3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [35]:
torch.add(x, 1)

tensor([[2, 3],
        [4, 5]])

In [36]:
torch.mul(x , 3)

tensor([[ 3,  6],
        [ 9, 12]])