In [2]:
import torch

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# 访问张量的shape属性，形状和张量中的元素
x.shape

torch.Size([12])

In [9]:
x.numel()

12

In [11]:
# 改变张量的形状而不改变元素的数量和元素值，使用reshape函数
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
X.shape

torch.Size([3, 4])

In [15]:
# 使用全0、1的其他常量或者从特定分布中随机采样的数字
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [21]:
# 通过包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
torch.tensor([[1, 2, 4], [3, 5, 7]]).shape

torch.Size([2, 3])

In [23]:
# 常见的标准运算符（+ - * / 和 **）都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [25]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [27]:
# 张量结合在一起
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x,y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
# 通过逻辑运算符构建二元张量
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
# 求和
x.sum()

tensor(66.)

In [33]:
# 即使形状不同，我们任然可以通过调用广播机制（broadcasting mechanism) 来执行按元素操作
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [35]:
a + b
# 这里通过广播机制，a 的列向量进行复制变成,b 同理
# tensor([[0, 0],
#         [1, 1],
#         [2, 2]])

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [40]:
# 元素访问
x = torch.arange(12, dtype= torch.float64).reshape((3, 4))

In [50]:
x, x[-1], x[1:2]

(tensor([[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [ 8.,  9., 10., 11.]], dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64),
 tensor([[10., 10., 10., 10.]], dtype=torch.float64))

In [48]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [51]:
# 多元素赋值我们只需要索引访问所有元素，然后为他们赋值

x[0:2, :] = 10
x

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [53]:
import numpy as np

A = x.numpy()
B = torch.tensor(A)

type(A), type(B)

(numpy.ndarray, torch.Tensor)